[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["Linus FÃ¤rnstrand <faern@faern.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.0"
